# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: FirstJob
    steps:
      - script: echo Hello, world!
        displayName: "Run a one-line script"

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'

  - job: SecondJob
    dependsOn: FirstJob
    steps:
      - script: echo This is from SecondJob

  - job: ThirdJob
    dependsOn: FirstJob
    steps:
      - script: echo This is from ThirdJob

  - job: FourthJob
    dependsOn: ThirdJob
    steps:
      - script: echo This is from FourthJob
